### ISSUE TITLE
Events - set up automatic deletion

### ISSUE THREAD

**Issue by laurenbenichou** [laurenbenichou/the_litography_project#23]
After event has passed, it should be destroyed. This should happen everyday.

**Comment by strickinato** [comment]
Do you want to destroy records? Or do you want to add a 'past' flag so it doesn't show on front end?

**Comment by laurenbenichou** [comment]
Destroy is better. We are going to have SO MANY by the end of the year. Better get rid of them. 



-- 
Lauren [Lo] Benichou
Interactive News Developer at Youth Radio | Co-Founder at The Lithography Project
www.laurenbenichou.com
510-305-2053

On February 23, 2015 at 4:22:22 PM, Aaron Strick (notifications@github.com) wrote:

Do you want to destroy records? Or do you want to add a 'past' flag so it doesn't show on front end?
